server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/university
    username: root
    password: letmein
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
